from __future__ import annotations

from iceberg_r2_lab.settings import Settings


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_identifier(value: str) -> str:
    """Quote a DuckDB identifier without treating it as SQL."""
    if not value:
        raise ValueError("DuckDB identifiers must not be empty.")

    return '"' + value.replace('"', '""') + '"'


def qualified_identifier(*parts: str) -> str:
    return ".".join(sql_identifier(part) for part in parts)


def generate_attach_sql(settings: Settings) -> str:
    alias = sql_identifier(settings.duckdb_catalog_alias)
    schema = qualified_identifier(settings.duckdb_catalog_alias, settings.namespace)
    table = qualified_identifier(
        settings.duckdb_catalog_alias,
        settings.namespace,
        settings.table,
    )
    warehouse = sql_quote(settings.warehouse)
    endpoint = sql_quote(settings.catalog_uri)
    token = sql_quote(settings.token)

    return f"""-- Generated by iceberg-r2-lab duckdb-sql.
-- This file contains a token. Do not commit it.
-- DuckDB CLI may store CREATE SECRET statements in command history.

INSTALL iceberg;
LOAD iceberg;

INSTALL httpfs;
LOAD httpfs;

CREATE SECRET r2_iceberg_secret (
    TYPE iceberg,
    TOKEN {token}
);

ATTACH {warehouse} AS {alias} (
    TYPE iceberg,
    SECRET r2_iceberg_secret,
    ENDPOINT {endpoint},
    SUPPORT_NESTED_NAMESPACES true
);

CREATE SCHEMA IF NOT EXISTS {schema};
USE {schema};

-- Example:
-- SELECT * FROM {table} LIMIT 20;
"""
