from __future__ import annotations

from iceberg_r2_lab.settings import Settings


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generate_attach_sql(settings: Settings) -> str:
    alias = settings.duckdb_catalog_alias
    warehouse = sql_quote(settings.warehouse)
    endpoint = sql_quote(settings.catalog_uri)
    token = sql_quote(settings.token)

    return f"""-- Generated by iceberg-r2-lab duckdb-sql.
-- This file contains a token. Do not commit it.
-- DuckDB CLI may store CREATE SECRET statements in command history.

INSTALL iceberg;
LOAD iceberg;

CREATE SECRET r2_iceberg_secret (
    TYPE iceberg,
    TOKEN {token}
);

ATTACH {warehouse} AS {alias} (
    TYPE iceberg,
    ENDPOINT {endpoint}
);

CREATE SCHEMA IF NOT EXISTS {alias}.{settings.namespace};
USE {alias}.{settings.namespace};

-- Example:
-- SELECT * FROM {alias}.{settings.namespace}.{settings.table} LIMIT 20;
"""
